<a class="anchor" id="0."></a>
# **Contents**

1. [Pytorch Basics](#1.)
* * [1.1. Autograde Example 1](#1.1.)
* * [1.2. Autograde Example 2](#1.2.)
* * [1.3. Dataset Pipeline to Feed Model](#1.3.)
* * [1.4. Pretrained Computer Vision Models](#1.4.)
* * [1.5. Save and Load the Model](#1.5.)
1. [Linear Regression](#2.)

1. [Logistic Regression](#3.)

1. [Feedforward Neural Network](#4.)


In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import torch
import torchvision
from torch import nn
from torchvision import transforms
from sklearn import datasets

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


[Go to Contents Menu](#0.)
<a class="anchor" id="1."></a>

# **1. Pytorch Basics**  

[Go to Contents Menu](#0.)
<a class="anchor" id="1.1."></a>

# **1.1. Autograde Example 1**  

In [3]:
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

print(x, w, b, "\n",x.item(), w.item(), b.item())

# Computional grap
y = w*x + b
#Compute gradient
y.backward()
print("x.grad:",x.grad, "\nw.grad:",w.grad, "\nb.grad:",b.grad)

tensor(1., requires_grad=True) tensor(2., requires_grad=True) tensor(3., requires_grad=True) 
 1.0 2.0 3.0
x.grad: tensor(2.) 
w.grad: tensor(1.) 
b.grad: tensor(1.)


[Go to Contents Menu](#0.)
<a class="anchor" id="1.2."></a>

# **1.2. Autograde Example 2**  

In [4]:
x = torch.randn(10, 3)
y = torch.randn(10, 2)

linear = nn.Linear(3, 2)

#Define loss function and optimizer
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

#forward pass
pred = linear(x)
#Compute loss
loss = loss_fn(pred, y)
print("loss:", loss.item())

#Backward pass
loss.backward()

#print gradients
print("w:", linear.weight.grad)
print("b:", linear.bias.grad)

# Step gradient descent
optimizer.step()


#After one step optimization
pred = linear(x)
loss = loss_fn(pred, y)
print("After one step loss:", loss.item())



loss: 0.6395232081413269
w: tensor([[ 0.3565, -0.1092, -0.1792],
        [-0.0296,  0.1045,  0.5430]])
b: tensor([ 0.3887, -0.1562])
After one step loss: 0.6330186128616333


[Go to Contents Menu](#0.)
<a class="anchor" id="1.3."></a>

# **1.3. Dataset Pipeline to Feed Model**  

In [5]:
train_dataset = torchvision.datasets.CIFAR10(root = "data",
                                            train=True,
                                            transform=transforms.ToTensor(),
                                            download=True)
image, label = train_dataset[0]
print(image.shape, label)

  0%|          | 0/170498071 [00:00<?, ?it/s]

Extracting data/cifar-10-python.tar.gz to data
torch.Size([3, 32, 32]) 6


In [6]:
train_dataloader = torch.utils.data.DataLoader(dataset=train_dataset,
                                              batch_size=64,
                                               shuffle=True)
data_iter = iter(train_dataloader)
images, labels = data_iter.next()
print(images.shape, labels.shape)

torch.Size([64, 3, 32, 32]) torch.Size([64])


In [7]:
import matplotlib.pyplot as plt
plt.figure(figsize=(5, 5))
for i in range(9):
    img = images[i]
    plt.subplot(3, 3 , i+1)
    plt.xticks([])
    plt.yticks([])
    plt.title(labels[i].item())
    plt.imshow(img.moveaxis(0, 2))
plt.show()

In [8]:
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self):
        #initialize file paths
        pass
    def __getitem__(self, index):
        # preprocess data and return x, y
        pass
    def __len__(self):
        # return length of dataset
        pass
    
    


[Go to Contents Menu](#0.)
<a class="anchor" id="1.4."></a>

# **1.4. Pretrained Computer Vision Models**  

In [9]:
print(*[name  for name in dir(torchvision.models) if "__" not in name], sep="\n")

AlexNet
DenseNet
GoogLeNet
GoogLeNetOutputs
Inception3
InceptionOutputs
MNASNet
MobileNetV2
MobileNetV3
ResNet
ShuffleNetV2
SqueezeNet
VGG
_GoogLeNetOutputs
_InceptionOutputs
_utils
alexnet
densenet
densenet121
densenet161
densenet169
densenet201
detection
googlenet
inception
inception_v3
mnasnet
mnasnet0_5
mnasnet0_75
mnasnet1_0
mnasnet1_3
mobilenet
mobilenet_v2
mobilenet_v3_large
mobilenet_v3_small
mobilenetv2
mobilenetv3
quantization
resnet
resnet101
resnet152
resnet18
resnet34
resnet50
resnext101_32x8d
resnext50_32x4d
segmentation
shufflenet_v2_x0_5
shufflenet_v2_x1_0
shufflenet_v2_x1_5
shufflenet_v2_x2_0
shufflenetv2
squeezenet
squeezenet1_0
squeezenet1_1
utils
vgg
vgg11
vgg11_bn
vgg13
vgg13_bn
vgg16
vgg16_bn
vgg19
vgg19_bn
video
wide_resnet101_2
wide_resnet50_2


In [10]:
print(*[name  for name in dir(torchvision.models.detection) if "_" not in name], sep="\n")

FasterRCNN
KeypointRCNN
MaskRCNN
RetinaNet
SSD
retinanet
rpn
ssd
ssdlite
transform


In [11]:
print(*[name  for name in dir(torchvision.models.segmentation) if "_" not in name], sep="\n")

DeepLabV3
FCN
LRASPP
deeplabv3
fcn
lraspp
segmentation


In [12]:
model = torchvision.models.mobilenet_v2(pretrained=True)
model.classifier[1] = nn.Linear(model.last_channel, 10)

sampels = torch.Tensor(64, 3 ,224 ,224)
outputs = model(sampels)
print(sampels.shape, outputs.shape)

Downloading: "https://download.pytorch.org/models/mobilenet_v2-b0353104.pth" to /root/.cache/torch/hub/checkpoints/mobilenet_v2-b0353104.pth


  0%|          | 0.00/13.6M [00:00<?, ?B/s]

torch.Size([64, 3, 224, 224]) torch.Size([64, 10])


In [13]:
model = torchvision.models.mobilenet_v2(pretrained=True)
# To fine tune model freeze layers
for parameter in model.parameters():
    parameter.require_grad = False
    
model.classifier[1] = nn.Linear(model.last_channel, 10)

[Go to Contents Menu](#0.)
<a class="anchor" id="1.5."></a>

# **1.5. Save and Load the Model**  

In [14]:
model_name = "mobilenetv2.pt"
torch.save(model, model_name)
model = torch.load(model_name)

In [15]:
torch.save(model.state_dict(), model_name)
model.load_state_dict(torch.load(model_name))

<All keys matched successfully>

[Go to Contents Menu](#0.)
<a class="anchor" id="2."></a>

# **2. Linear Regression**  

In [16]:
boston = datasets.load_boston()

In [17]:
dir(boston)

['DESCR', 'data', 'feature_names', 'filename', 'target']

In [18]:
X = boston.data
y = boston.target
print(X.shape, y.shape)
print(X.dtype, y.dtype)

from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(X)
X = ss.transform(X)

(506, 13) (506,)
float64 float64


In [19]:
X = torch.tensor(X, dtype=torch.float)

y = torch.tensor(y, dtype=torch.float).view(-1, 1)

In [20]:
class BostonDataset(torch.utils.data.Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y
    def __getitem__(self, index):
        return X[index], y[index]
    def __len__(self):
        return len(X)
    

train_dataset = BostonDataset(X, y)
#train_dataset = torch.utils.data.TensorDataset(X, y)
train_dataloader = torch.utils.data.DataLoader(dataset=train_dataset,
                                              batch_size=1,
                                               shuffle=True)
data_iter = iter(train_dataloader)
x_batch, y_batch = data_iter.next()
print(x_batch.shape, y_batch.shape)

torch.Size([1, 13]) torch.Size([1, 1])


In [21]:
model = torch.nn.Sequential(nn.Linear(X.shape[1], 1))
print(model(x_batch))

tensor([[0.5209]], grad_fn=<AddmmBackward>)


In [22]:


epochs = 50
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)


In [23]:
for  epoch in range(epochs):
    for X_batch, y_batch in train_dataloader:
        #X_batch = torch.FloatTensor(X_batch)
        #y_batch = torch.FloatTensor(y_batch)
        
        pred = model(X_batch)
        loss = loss_fn(pred, y_batch)
        # print(loss.item(), end=" ")
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
    print(f"{epoch + 1}/{epochs} loss:{loss.item()}")

1/50 loss:24.108642578125
2/50 loss:8.427945137023926
3/50 loss:0.7760677933692932
4/50 loss:8.54776668548584
5/50 loss:15.905033111572266
6/50 loss:1.3578671216964722
7/50 loss:0.4448760449886322
8/50 loss:649.3167724609375
9/50 loss:25.704509735107422
10/50 loss:0.033466871827840805
11/50 loss:23.68533706665039
12/50 loss:13.492220878601074
13/50 loss:165.93118286132812
14/50 loss:0.10408145934343338
15/50 loss:48.52522277832031
16/50 loss:1.3469717502593994
17/50 loss:3.7087361812591553
18/50 loss:0.4313327372074127
19/50 loss:12.19276237487793
20/50 loss:24.620193481445312
21/50 loss:0.24505604803562164
22/50 loss:10.570070266723633
23/50 loss:0.16637451946735382
24/50 loss:29.047786712646484
25/50 loss:3.1638920307159424
26/50 loss:7.054691314697266
27/50 loss:0.00012535347195807844
28/50 loss:37.88692092895508
29/50 loss:2.513939619064331
30/50 loss:1.3571516275405884
31/50 loss:3.659168004989624
32/50 loss:23.652006149291992
33/50 loss:0.06044015660881996
34/50 loss:1.7734384536

In [24]:
predicted = model(X).detach().numpy()
predicted.shape

(506, 1)

In [25]:
for i in range(10):
    print(y[i], predicted[i])

tensor([24.]) [30.005413]
tensor([21.6000]) [25.0703]
tensor([34.7000]) [30.497225]
tensor([33.4000]) [28.517868]
tensor([36.2000]) [27.87246]
tensor([28.7000]) [25.23675]
tensor([22.9000]) [23.038605]
tensor([27.1000]) [19.638674]
tensor([16.5000]) [11.765533]
tensor([18.9000]) [18.997108]


In [26]:

plt.plot(y.flatten(), label='Original data')
plt.plot(predicted.flatten(), label='Fitted line')
plt.legend()
plt.show()

[Go to Contents Menu](#0.)
<a class="anchor" id="3."></a>

# **3. Logistic Regression**  

In [27]:
breast_cancer = datasets.load_breast_cancer()
dir(breast_cancer)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [28]:
X = breast_cancer.data
y = breast_cancer.target
print(np.unique(y))

df  = pd.DataFrame(X)
df.columns = breast_cancer.feature_names
df['target'] = y
df.head()

[0 1]


mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [29]:
# df.info()

In [30]:
#dir(torch)

In [31]:
X = torch.tensor(X, dtype=torch.float)

y = torch.tensor(y).view(-1, 1)

In [32]:
class BreastCancerDataset(torch.utils.data.Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y
    def __getitem__(self, idx):
        return X[idx], y[idx]
    def __len__(self):
        return len(X)
    
train_dataset = BreastCancerDataset(X, y)

train_dataloader = torch.utils.data.DataLoader(dataset=train_dataset,
                                              batch_size=1,
                                              shuffle=True)


In [33]:
train_dataloader_iter = iter(train_dataloader)
x_batch, y_batch = next(train_dataloader_iter)
print(x_batch.shape, y_batch.shape)

torch.Size([1, 30]) torch.Size([1, 1])


In [34]:
from sklearn.model_selection import train_test_split
X = breast_cancer.data
y = breast_cancer.target
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.25, random_state=35)

train_dataset = torch.utils.data.TensorDataset(torch.from_numpy(X_train).float(),
                                 torch.from_numpy(y_train).long())
train_dataloader = torch.utils.data.DataLoader(train_dataset, batch_size=32, shuffle=False)

test_dataset = torch.utils.data.TensorDataset(torch.from_numpy(X_test).float(),
                                 torch.from_numpy(y_test).long())
test_dataloader = torch.utils.data.DataLoader(test_dataset, batch_size=32, shuffle=False)

In [35]:
# model = nn.Linear(X.shape[1], 2)
model = torch.nn.Sequential(nn.Linear(X.shape[1], 2))

In [36]:
loss_fn  = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)

In [37]:
epochs = 100
for  epoch in range(epochs):
    for X_batch, y_batch in train_dataloader:
        #X_batch = torch.FloatTensor(X_batch)
        #y_batch = torch.FloatTensor(y_batch)
        y_batch = y_batch.squeeze_()
        pred = model(X_batch)
        loss = loss_fn(pred, y_batch)
        # print(loss.item(), end=" ")
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
    if epoch % 20 == 0:
        print(f"{epoch + 1}/{epochs} loss:{loss.item()}")



1/100 loss:271.30560302734375
21/100 loss:130.91983032226562
41/100 loss:54.13389205932617
61/100 loss:77.64628601074219
81/100 loss:81.10774230957031


In [38]:
y_train_pred = model(torch.tensor(X_train, dtype=torch.float)).detach().numpy()
y_train_pred.shape

(426, 2)

In [39]:
from sklearn import metrics
print(metrics.accuracy_score(np.argmax(y_train_pred, axis=1), y_train))

0.9154929577464789


In [40]:
y_test_pred = model(torch.tensor(X_test, dtype=torch.float)).detach().numpy()

In [41]:
print(metrics.accuracy_score(np.argmax(y_test_pred, axis=1), y_test))
print(metrics.confusion_matrix(np.argmax(y_test_pred, axis=1), y_test))
print(metrics.classification_report(np.argmax(y_test_pred, axis=1), y_test))

0.9230769230769231
[[44  2]
 [ 9 88]]
              precision    recall  f1-score   support

           0       0.83      0.96      0.89        46
           1       0.98      0.91      0.94        97

    accuracy                           0.92       143
   macro avg       0.90      0.93      0.92       143
weighted avg       0.93      0.92      0.92       143



[Go to Contents Menu](#0.)
<a class="anchor" id="4."></a>

# **4. Feedforward Neural Network**  

In [47]:
# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("device:", device)

device: cpu


In [44]:
train_dataset = torchvision.datasets.MNIST(root="data",
                                          train=True,
                                          transform=transforms.ToTensor(),
                                          download=True)
test_dataset = torchvision.datasets.MNIST(root="data",
                                        train=False,
                                        transform=transforms.ToTensor())

In [45]:
train_dataloader = torch.utils.data.DataLoader(dataset=train_dataset,
                                              batch_size=32,
                                              shuffle=True)
test_dataloader = torch.utils.data.DataLoader(dataset=test_dataset,
                                             batch_size=32,
                                             shuffle=False)

In [46]:
x_batch, y_batch = next(iter(train_dataloader))
print(x_batch.shape, y_batch.shape)

torch.Size([32, 1, 28, 28]) torch.Size([32])


In [52]:
len(train_dataloader)*32, len(test_dataloader)*32

(60000, 10016)

In [56]:
class NN(nn.Module):
    def __init__(self, input_size, hidden_size, num_class):
        super(NN, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, num_class)
        
    def forward(self, x):
        output = self.fc1(x)
        output = self.relu(output)
        output = self.fc2(output)
        return output

model = NN(28*28, 512, 10).to(device)

In [57]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [58]:
epochs = 10
for epoch in range(epochs):
    for i, (images, labels) in enumerate(train_dataloader):
        images = images.reshape(-1, 28*28).to(device)
        labels = labels.to(device)
        
        pred = model(images)
        loss = loss_fn(pred, labels)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        
    print(f"{epoch+1}/{epochs} loss:{loss.item()}")
        

1/10 loss:0.10619664937257767
2/10 loss:0.02134798653423786
3/10 loss:0.011553402990102768
4/10 loss:0.010417895391583443
5/10 loss:0.011909245513379574
6/10 loss:0.005639753304421902
7/10 loss:0.006690812762826681
8/10 loss:0.0027996187563985586
9/10 loss:0.06105399876832962
10/10 loss:0.0003811414644587785


In [66]:
def evaluate(model, dataloader):
    correct, total = 0, 0
    with torch.no_grad():
        for i, (images, labels) in enumerate(dataloader):
            images = images.reshape(-1, 28*28).to(device)
            labels = labels.to(device)

            outputs = model(images)
            _, predictions = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predictions == labels).sum().item()
    return correct/total

In [67]:
print("train acc:{:.3f}".format(evaluate(model, train_dataloader)))

train acc:0.997


In [68]:
 print("test acc:{:.3f}".format(evaluate(model, test_dataloader)))

test acc:0.980
